name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: build vuepress to github page
      uses: JamesIves/github-pages-deploy-action@maste
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_GH_PAGE }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: .vuepress/dist # The folder the action should deploy.
        BUILD_SCRIPT: yarn install && yarn run docs:build
