name: deploy github pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: build vuepress to github page
      shell: bash
      run: |
        chmod +x deploy.sh
        ./deploy.sh
      env:
        GITHUB_PAGE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: .vuepress/dist
        BUILD_SCRIPT: npm install && npm run docs:build     
